[MICA-14067] saml2 4.0.2 rebase arterys
morpheus-med/saml2 pull request #7
Opened 2023-11-22 18:32 UTC by nsvarich

2023-11-27 16:28 UTC, tjugdev approved these changes

2023-11-27 17:20 UTC, nsvarich commented on test/saml2.coffee
>            "Expected to find an SingleLogoutService with location 'htps://sp.example.com/assert'")
Change to logout

2023-11-27 18:06 UTC, hinshaw-arterys commented on test/saml2.coffee
> +          , "Expected to find a SingleLogoutService with redirect binding and location 'https://sp.example.com/logout'"
Says "with redirect binding", but looks like a POST binding 2 lines above?  (bindings:HTTP-POST)

2023-11-27 18:23 UTC, hinshaw-arterys approved these changes

2023-12-04 17:51 UTC, hinshaw-arterys commented on test/data/good_assertion.xml
> +</Assertion>
Missing final newline

2023-12-04 17:52 UTC, hinshaw-arterys commented on test/data/good_response_twice_signed.xml
> +</samlp:Response>
missing final newline

2023-12-04 17:52 UTC, hinshaw-arterys commented on test/data/good_response_twice_signed_dsig_ns_at_top.xml
> +</samlp:Response>
missing final newline

2023-12-04 17:52 UTC, hinshaw-arterys commented on test/data/response_external_signed_assertion.xml
> +PHNhbWxwOlJlc3BvbnNlIHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiIElEPSJfMiIgVmVyc2lvbj0iMi4wIiBJblJlc3BvbnNlVG89Il8xIiBEZXN0aW5hdGlvbj0iaHR0cHM6Ly9zcC5leGFtcGxlLmNvbS9hc3NlcnQ
missing final newline

2023-12-04 17:52 UTC, hinshaw-arterys commented on test/data/response_notbefore_future_encrypted.xml
> +PHNhbWxwOlJlc3BvbnNlIHhtbG5zOnNhbWxwPSJ1cm46b2FzaXM6bmFtZXM6dGM6U0FNTDoyLjA6cHJvdG9jb2wiIHhtbG5zOnNhbWw9InVybjpvYXNpczpuYW1lczp0YzpTQU1MOjIuMDphc3NlcnRpb24iIElEPSJfMiIgVmVyc2lvbj0iMi4wIiBJblJlc3BvbnN
missing final newline

2023-12-04 17:53 UTC, hinshaw-arterys commented on test/data/response_notbefore_future_encrypted_then_signed.xml
> +</xenc:EncryptedData></saml:EncryptedAssertion></samlp:Response>
missing final newline

2023-12-04 17:53 UTC, hinshaw-arterys commented on test/data/response_notbefore_future_signed.xml
> +</samlp:Response>
missing final newline

2023-12-04 17:53 UTC, hinshaw-arterys commented on test/data/response_notbefore_future_signed_then_encrypted.xml
> +</xenc:EncryptedData></EncryptedAssertion></samlp:Response>
missing final newline

2023-12-04 17:55 UTC, hinshaw-arterys requested changes
Several files missing final newline.  (Not a huge deal, but I've seen that cause hard-to-solve weirdness before.)

2023-12-04 19:02 UTC, hinshaw-arterys commented on test/data/good_assertion.xml
> +</Assertion>
Nick found that these missing newlines are coming from upstream and we haven't touched them.  So let's leave them as-is.

2023-12-04 19:37 UTC, merged